tunnel: nutria-pro-prod
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: api.nutria-pro.com
    service: http://api:8000
  - hostname: chat.nutria-pro.com
    service: http://chatwoot-web:3000
  - hostname: admin-api.nutria-pro.com
    service: http://api:8000
  - service: http_status:404
